### ISSUE TITLE
Suggestion:  move all run configuration to a scala typesafe configuration object, rather than 

### ISSUE THREAD

**Issue by dannyprok** [hmrc/ui-test-template.g8#8]
Can we consolidate the test run configuration into one scala typesafe configuration object rather than have the configuration spread across multiple files/classes?

Use https://github.com/lightbend/config rather than properties files

Perhaps include the following all in one configuration file:
- https://github.com/hmrc/ui-test-template.g8/blob/master/src/main/g8/src/test/scala/uk/gov/hmrc/test/ui/pages/BasePage.scala#L38-L41
- https://github.com/hmrc/ui-test-template.g8/blob/master/src/main/g8/src/test/scala/uk/gov/hmrc/test/ui/pages/BasePage.scala#L47-L50
- https://github.com/hmrc/ui-test-template.g8/blob/master/src/main/g8/src/test/resources/environment.properties

The config object could take a form like the following:
```
test {
  url = "http://localhost"
  frontendPort = 9949
  productionRoute = "/auth-login-stub"  

  qa {
    url = "http://qa.placeholder.url"
  }

  externalTest {
    url = "http://et.placeholder.url"
  }
}
```

**Comment by CEPoole** [comment]
We should consider change the default implementation of BasePage to keep in mind the use case of multiple frontend services in one flow.
Currently, the template assumes a single frontend route and port but this might be a good opportunity to consider what the code and config would look like with support for more than one

**Comment by craigtd** [comment]
How about a pattern whereby we have a trait for each front end service in use which extends BasePage and use this to define the port when run locally along with the URL. So FrontEndApp1Page & FrontEndApp2Page extends BasePage and overrrides port. Individual Page traits would then extend FrontEndApp1Page or FrontEndApp2Page rather than BasePage directly and inherit the url. This would help us keep the config object simple. The afi-acceptance-tests are somewhat close to this pattern and have a function to recreate the local url pulling in the port number depending on the environment.

https://github.com/hmrc/afi-acceptance-tests/blob/master/src/test/scala/afi/pages/WebPage.scala#L21
https://github.com/hmrc/afi-acceptance-tests/blob/master/src/test/scala/afi/pages/taxhistory/SelectClientPage.scala#L8

I am no longer working on afi-acceptance-tests but could demo something in a fork if that helps.

**Comment by ejayaraman** [comment]
The template now uses Typesafe config. The changes have been merged into master.
